

export const GET_ALL_CATEGORY="GET_ALL_CATEGORY";
export const GET_ERROR="GET_ERROR";
export const CREATE_CATEGORIE ="CREATE_CATEGORIE";


export const GET_ALL_BRAND = "GET_ALL_BRAND";

export const CREATE_SUBCATEGORIE ="CREATE_SUBCATEGORIE";
